import Vue from 'vue'
import { Row, Col, Button, Grid, GridItem, Swipe, SwipeItem, Lazyload, Icon, Image, Tab, Tabs, Field, CellGroup, Toast, List, Cell } from 'vant'

Vue.use(Row)
  .use(Col)
  .use(Button)
  .use(Grid)
  .use(GridItem)
  .use(Swipe)
  .use(SwipeItem)
  .use(Lazyload)
  .use(Icon)
  .use(Image)
  .use(Tab)
  .use(Tabs)
  .use(Field)
  .use(CellGroup)
  .use(Toast)
  .use(List)
  .use(Cell)
